version: "3.7"

services:
    mysql:
        platform: linux/x86_64
        image: mysql:8.0
        environment:
            - MYSQL_DATABASE=kickback
            - MYSQL_USER=testuser
            - MYSQL_PASSWORD=testpw
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - spring-boot-mysql-network
        ports:
            - 33061:3306
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 20s
            retries: 10

    app:
        build: .
        ports:
            - 9091:9090
        networks:
            - spring-boot-mysql-network
        depends_on:
            mysql:
                condition: service_healthy

networks:
    spring-boot-mysql-network:
        driver: bridge
